lib/b2ml_web/router.ex
defmodule B2mlWeb.Router do
  use B2mlWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug B2mlWeb.Plugs.SetLocale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", B2mlWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/teachers", TeacherController
    resources "/students", StudentController
    resources "/classes", ClassController
  end

  # Other scopes may use custom stacks.
  # scope "/api", B2mlWeb do
  #   pipe_through :api
  # end
end

lib/b2ml_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "B2ml School" %></h1>
  <p><%= gettext "A place where you can learn" %><br/><%= gettext "and train your skills" %></p>
</section>

<section class="row">
  <article class="column">
    <h2><%= gettext "Teachers" %></h2>
    <ul>
      <li>
        <%= link gettext("List all teachers"), to: Routes.teacher_path(@conn, :index) %>
      </li>
      <li>
        <%= link gettext("Add new teacher"), to: Routes.teacher_path(@conn, :new) %>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2><%= gettext "Students" %></h2>
    <ul>
      <li>
        <%= link gettext("List all students"), to: Routes.student_path(@conn, :index) %>
      </li>
      <li>
        <%= link gettext("Register a student"), to: Routes.student_path(@conn, :new) %>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2><%= gettext "Classes" %></h2>
    <ul>
      <li>
        <%= link gettext("List all classes"), to: Routes.class_path(@conn, :index) %>
      </li>
      <li>
        <%= link gettext("Create new class"), to: Routes.class_path(@conn, :new) %>
      </li>
    </ul>
  </article>
</section>